environments:
  development:
    branch_pattern: "^development$"
    environment: "Development"
    project_id: "unops-opportunityplus-dev"
    repo_name: "cloud-run-images"
    image_name: "cloud-run-images/external-data-service-dev"
    service_name: "external-data-service-dev"
    region: "europe-west4"
    sql_conn_string: "unops-opportunityplus-dev:europe-west4:unops-opportunityplus-dev-postgres-001"
    vpc_connector: "projects/unops-opportunityplus-dev/locations/europe-west4/connectors/opportunityplus-dev-vpc"
    secrets: "ConnectionStrings__DefaultConnection=Dev_DB_Connection_String:latest,ConnectionStrings__ApplicationConnection=Dev_Monitoring_DB_Connection_String:latest"
    env_vars: "ASPNETCORE_ENVIRONMENT=Development,GOOGLE_CLOUD_PROJECT=unops-opportunityplus-dev,ExternalDataService__ConfigurationPath=../ExternalDataService/config"
    credentials_id: "cicd-sa-oplus-dev"
    service_account: "cicd-sa@unops-opportunityplus-dev.iam.gserviceaccount.com"
    dockerfile: "Dockerfile"
    port: "8080"
    min_instances: "0"
    max_instances: "3"
    memory: "2Gi"
    cpu: "1"
    timeout: "900"