environments:
  development:
    branch_pattern: "^development$"
    environment: "QA"
    project_id: "unops-opportunityplus-qa"
    repo_name: "cloud-run-images"
    image_name_main: "cloud-run-images/opportunityplus-qa"
    image_name_ai: "cloud-run-images/opportunityplus-ai-qa"
    service_name_main: "opportunityplus-qa"
    service_name_ai: "opportunityplus-ai-qa"
    region: "europe-west4"
    sql_conn_string: "unops-opportunityplus-qa:europe-west4:unops-opportunityplus-qa-postgres-001"
    vpc_connector: "projects/unops-opportunityplus-qa/locations/europe-west4/connectors/opportunityplus-qa-vpc"
    secrets_main: "QA_DB_Connection_String=QA_DB_Connection_String:latest,GoogleDriveServiceAccount_JSON=GoogleDriveServiceAccount_JSON:latest,AI_Setup_Secret=AI_Setup_Secret:latest"
    env_vars_ai: "CURRENT_ENV=qa,GOOGLE_CLOUD_PROJECT=unops-opportunityplus-qa,GOOGLE_CLOUD_LOCATION=europe-west4,GOOGLE_GENAI_USE_VERTEXAI=TRUE"
    credentials_id: "cicd-sa-oplus-qa"
    dockerfile_main: "Dockerfile.qa"
    port_main: "7123"
    port_ai: "8080"
    ai_min_instances: "1"
    ai_max_instances: "10"
    ai_memory: "2Gi"