using Microsoft.EntityFrameworkCore;
using UNOPS.PAO.Domain.Entities;
using UNOPS.PAO.Domain.Enums;
using UNOPS.PAO.UNOPSDataAccess.Context;

namespace UNOPS.PAO.UNOPSDataAccess.Seed.Seeders;

public static class OutputSeeder
{
    public static async Task SeedOutputsAsync(UNOPSAppDbContext context)
    {
        Console.WriteLine(" Seeding Outputs...");

        var units = await context.Set<Unit>().ToListAsync();
        var projectCategories = await context.Set<ProjectCategory>().ToListAsync();

        var outputsToSeed = GetOutputsToSeed(units, projectCategories);
        var existingOutputs = await context.Set<Output>().ToListAsync();

        var outputNamesToKeep = outputsToSeed.Select(o => o.OutputName).ToHashSet();

        foreach (var outputData in outputsToSeed)
        {
            var existingOutput = existingOutputs.FirstOrDefault(o => 
                o.OutputName == outputData.OutputName && 
                o.OutputGroup == outputData.OutputGroup &&
                o.OutputSubGroup == outputData.OutputSubGroup);

            if (existingOutput == null)
            {
                context.Set<Output>().Add(outputData);
                Console.WriteLine($"   Inserted Output: {outputData.OutputGroup} - {outputData.OutputName}");
            }
            else
            {
                bool hasChanges = false;

                if (existingOutput.Name != outputData.Name) { existingOutput.Name = outputData.Name; hasChanges = true; }
                if (existingOutput.Description != outputData.Description) { existingOutput.Description = outputData.Description; hasChanges = true; }
                if (existingOutput.UnitId != outputData.UnitId) { existingOutput.UnitId = outputData.UnitId; hasChanges = true; }
                if (existingOutput.ProjectCategoryId != outputData.ProjectCategoryId) { existingOutput.ProjectCategoryId = outputData.ProjectCategoryId; hasChanges = true; }
                if (existingOutput.OutputServiceLine != outputData.OutputServiceLine) { existingOutput.OutputServiceLine = outputData.OutputServiceLine; hasChanges = true; }
                if (existingOutput.Status != outputData.Status) { existingOutput.Status = outputData.Status; hasChanges = true; }
                if (existingOutput.IsDeleted) { existingOutput.IsDeleted = false; hasChanges = true; }

                if (hasChanges) { Console.WriteLine($"   Updated Output: {outputData.OutputGroup} - {outputData.OutputName}"); }
            }
        }

        await context.SaveChangesAsync();
        Console.WriteLine($" Outputs seeding completed - Total: {outputsToSeed.Count}\n");
    }

    private static List<Output> GetOutputsToSeed(List<Unit> units, List<ProjectCategory> projectCategories)
    {
        var outputs = new List<Output>();

        // Helper to get Unit and ProjectCategory
        var days = units.FirstOrDefault(u => u.Code == "DAYS")?.Id;
        var no = units.FirstOrDefault(u => u.Code == "NO")?.Id;
        var kg = units.FirstOrDefault(u => u.Code == "KG")?.Id;
        var ltr = units.FirstOrDefault(u => u.Code == "LTR")?.Id;
        var km = units.FirstOrDefault(u => u.Code == "KM")?.Id;
        var km2 = units.FirstOrDefault(u => u.Code == "KM2")?.Id;
        var hectares = units.FirstOrDefault(u => u.Code == "Hectares")?.Id;
        
        var cat1 = projectCategories.FirstOrDefault(c => c.Code == "Category 1")?.Id;
        var cat2 = projectCategories.FirstOrDefault(c => c.Code == "Category 2")?.Id;
        var cat3 = projectCategories.FirstOrDefault(c => c.Code == "Category 3")?.Id;

        outputs.Add(new Output { Name = "Technical assistance: Finance - Advisory", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: finance", OutputName = "Technical assistance: Finance - Advisory", Description = "Providing advice and/or support in person or in a virtual format, where UNOPS is not responsible or liable for the actual implementation in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: Finance - Implementation", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: finance", OutputName = "Technical assistance: Finance - Implementation", Description = "Implementing services in person or in a virtual format, where UNOPS is both responsible and liable for the services in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: HR - Advisory", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: HR", OutputName = "Technical assistance: HR - Advisory", Description = "Providing advice and/or support in person or in a virtual format, where UNOPS is not responsible or liable for the actual implementation in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Human resources", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: HR - Implementation", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: HR", OutputName = "Technical assistance: HR - Implementation", Description = "Implementing services in person or in a virtual format, where UNOPS is both responsible and liable for the services in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Human resources", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: Infrastructure - Advisory", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: infrastructure", OutputName = "Technical assistance: Infrastructure - Advisory", Description = "Providing advice and/or support in person or in a virtual format, where UNOPS is not responsible or liable for the actual implementation in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: Procurement - Advisory", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: procurement", OutputName = "Technical assistance: Procurement - Advisory", Description = "Providing advice and/or support in person or in a virtual format, where UNOPS is not responsible or liable for the actual implementation in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: Procurement - Implementation", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: procurement", OutputName = "Technical assistance: Procurement - Implementation", Description = "Implementing services in person or in a virtual format, where UNOPS is both responsible and liable for the services in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: Project Management - Advisory", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: project management", OutputName = "Technical assistance: Project Management - Advisory", Description = "Providing advice and/or support in person or in a virtual format, where UNOPS is not responsible or liable for the actual implementation in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Project Management", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical assistance: Project Management - Implementation", OutputGroup = "Assistance days", OutputSubGroup = "Technical assistance: project management", OutputName = "Technical assistance: Project Management - Implementation", Description = "Implementing services in person or in a virtual format, where UNOPS is both responsible and liable for the services in the areas of project/programme design, planning and implementation. An assistance day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Project Management", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Cash for work implementation: Infrastructure", OutputGroup = "Cash for work implementation", OutputSubGroup = "Cash for work implementation: Infrastructure", OutputName = "Cash for work implementation: Infrastructure", Description = "Work days generated via the cash payments provided to beneficiaries on the condition that they undertake designated infrastructure-related work. Beneficiary participation is usually restricted to time-bound cycles (e.g., four to six weeks) and payment for work on a cash for work (CfW) project can be made in the form of cash, vouchers (if necessary) or e-transfers. The number of days can be calculated by multiplying the number of beneficiaries by the days of work each of them generated via the cash payments.", UnitId = days, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Cash for work implementation: Other (including selection)", OutputGroup = "Cash for work implementation", OutputSubGroup = "Cash for work implementation: Other (including selection)", OutputName = "Cash for work implementation: Other (including selection)", Description = "Work days generated via the cash payments provided to beneficiaries which are selected by the UNOPS on the condition that they undertake designated work other than infrastructure nature. Beneficiary participation is usually restricted to time-bound cycles (e.g., four to six weeks) and payment for work on a cash for work (CfW) project can be made in the form of cash, vouchers (if necessary) or e-transfers. The number of days can be calculated by multiplying the number of beneficiaries by the days of work each of them generated via the cash payments.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Cash for work implementation: Other (under preselection)", OutputGroup = "Cash for work implementation", OutputSubGroup = "Cash for work implementation: Other (under preselection)", OutputName = "Cash for work implementation: Other (under preselection)", Description = "Work days generated via the cash payments provided to beneficiaries which are preselected by the partner on the condition that they undertake designated work other than infrastructure nature. Beneficiary participation is usually restricted to time-bound cycles (e.g., four to six weeks) and payment for work on a cash for work (CfW) project can be made in the form of cash, vouchers (if necessary) or e-transfers. The number of days can be calculated by multiplying the number of beneficiaries by the days of work each of them generated via the cash payments.", UnitId = days, ProjectCategoryId = cat1, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Prefabricated residential buildings and structures", OutputGroup = "Goods", OutputSubGroup = "Accommodation/shelter", OutputName = "Prefabricated residential buildings and structures", Description = "Single family residential structures that were pre-constructed at one location and erected at another location. Covers houses, mobile homes, cabins, garages, gazebos and home kitchens (UNSPSC codes 95141601-06).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Agricultural, forestry and landscape machinery and equipment", OutputGroup = "Goods", OutputSubGroup = "Agriculture", OutputName = "Agricultural, forestry and landscape machinery and equipment", Description = "Covers among others; ploughs, balers and weeders (UNSPSC codes: 21101501-2601).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Construction material supplies, others", OutputGroup = "Goods", OutputSubGroup = "Construction materials", OutputName = "Construction material supplies, others", Description = "Construction materials supplies (UNSPSC codes: 30100000-265802).", UnitId = kg, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Container and storage, including their accessories and supplies", OutputGroup = "Goods", OutputSubGroup = "Container and Storage", OutputName = "Container and storage, including their accessories and supplies", Description = "Containerization or storage items and their accessories for the purpose of storing or transporting products for future use, such as containers and their scanning accessories (UNSPSC codes: 24111501-141700).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Demining and disarmament equipment", OutputGroup = "Goods", OutputSubGroup = "Demining and disarmament", OutputName = "Demining and disarmament equipment", Description = "Covers among others; explosives control equipment accessories and suppliers (UNSPSC codes: 46151800-02), demining equipment and related products (UNSPSC codes: 46221500-13).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Domestic furnishing and appliances", OutputGroup = "Goods", OutputSubGroup = "Domestic furnishing and appliances", OutputName = "Domestic furnishing and appliances", Description = "Covers among other; domestic appliances and electronics (UNSPSC codes: 52000000-161600), domestic furniture (UNSPSC codes: 56100000-1900).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Developmental and professional teaching aids and materials and accessories and supplies", OutputGroup = "Goods", OutputSubGroup = "Educational items", OutputName = "Developmental and professional teaching aids and materials and accessories and supplies", Description = "Covers among others; middle school math kits, history charts or posters and dissection kits or supplies (UNSPSC codes: 60101001 û 60121253).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Fuel for vehicles or machinery", OutputGroup = "Goods", OutputSubGroup = "Fuel", OutputName = "Fuel for vehicles or machinery", Description = "Any liquid fuel  (UNSPSC codes: 15100000-1513).", UnitId = ltr, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Child care products, personal care products", OutputGroup = "Goods", OutputSubGroup = "Health", OutputName = "Child care products, personal care products", Description = "Products related to child and personal care (UNSPSC codes: 53131501-651, 56101800)", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Medical facility products", OutputGroup = "Goods", OutputSubGroup = "Health", OutputName = "Medical facility products", Description = "Covers among others; patient care beds or accessories for general use, wheelchairs and gurneys or scissor lifts (UNSPSC codes 42191501-606).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Medical measuring and observing and testing equipment - diagnostics kits", OutputGroup = "Goods", OutputSubGroup = "Health", OutputName = "Medical measuring and observing and testing equipment - diagnostics kits", Description = "Medical measuring, observing and testing equipment or other diagnostic kit used in the diagnosis of patients (UNSPSC codes 41115800-68).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Medical supplies", OutputGroup = "Goods", OutputSubGroup = "Health", OutputName = "Medical supplies", Description = "Covers among others; propane (UNSPSC code: 49121508); first aid-, response- and search, rescue kits (UNSPSC codes: 42172001-17); syringes, hypodermic needles and needle protectors (UNSPSC codes: 42142601-20); condoms (UNSPSC code: 53131622) and all other medical supplies not included in the previous UNSPSCs. The count is per unit, not per package of units.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Mosquito nets", OutputGroup = "Goods", OutputSubGroup = "Health", OutputName = "Mosquito nets", Description = "Fine mesh of cotton, polyester or nylon which can exclude insects such as mosquitos and flies without greatly reducing visibility or air flow. The mesh may be treated with insecticide of some form. The count is for individual nets (UNSPSC code 49121508).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Prefabricated medical buildings and structures", OutputGroup = "Goods", OutputSubGroup = "Health", OutputName = "Prefabricated medical buildings and structures", Description = "Buildings and structures used for medical purposes that were pre-constructed at one location and erected at another location (UNSPSCs 95141900-04)", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Vials/tablets/capsules of drugs", OutputGroup = "Goods", OutputSubGroup = "Health", OutputName = "Vials/tablets/capsules of drugs", Description = "Cover among others; drugs to treat amebic and trichonomal infections and antimalarial agents for malaria infections (UNSPSC codes: 51101602-2900); antiviral drugs for treating bacterial infections, e.g. tuberculosis, HIV (UNSPSC codes: 51281501-1504); all other types of vials/tablets/capsules which are not covered by the rest of the list. Each unit of the product should be counted.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Emergency relief items procured; others", OutputGroup = "Goods", OutputSubGroup = "Humanitarian", OutputName = "Emergency relief items procured; others", Description = "Tents (UNSPSC code: 49121503) and all other types of emergency relief items.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Prefabricated emergency relief buildings and structures", OutputGroup = "Goods", OutputSubGroup = "Humanitarian", OutputName = "Prefabricated emergency relief buildings and structures", Description = "Structures providing shelter that were pre-constructed at one location and erected at another location. Covers shelters, tents, halls and container units (UNSPSC codes: 95141801-03).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Information and communications technology equipment and software", OutputGroup = "Goods", OutputSubGroup = "ICT", OutputName = "Information and communications technology equipment and software", Description = "Covers among others; mobile phones, fixed phones, satellite phones and two way radios (UNSPSC codes: 43191501-635);  motherboards, hard disk drives, multimedia storage holders (UNSPSC codes: 43201401-2223); notebook computers, desktop computers, computer services (UNSPSC codes: 43211501-2201); networking accesories, networking equipment, networking platforms (UNSPSC codes: 43221501-3343); office suite software, enterprise system management software and project management software (UNSPSC codes: 43231501-3701).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Ambulances", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Ambulances", Description = "Motor vehicles which are explicitly used for medical/health purposes (UNSPSC codes: 25101703, 25101713, 25101715).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Armoured motor vehicles", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Armoured motor vehicles", Description = "Passenger type vehicle equipped with armor reinforced body and frame (UNSPSC code: 25101510).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Buses", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Buses", Description = "A large communal road motor vehicle, having a long body, equipped with seats or benches for passengers, typically operated as part of a scheduled service (UNSPSC codes 25101501-02).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Cars,station wagons, light trucks, sport utility vehicles", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Cars,station wagons, light trucks, sport utility vehicles", Description = "Covers among others; road vehicles (UNSPSC codes: 25101503-04); light trucks, sport utility vehicles (SUV) (UNSPSC code: 25101507).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Construction machinery", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Construction machinery", Description = "Motor vehicles which are explicitly used for infrastructure construction purposes (UNSPSC codes: 22000000-102000).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Mobile healthcare centre", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Mobile healthcare centre", Description = "Motor vehicles with clinics and/or laboratory facilities which are utilized for direct medical attention to patients (UNSPSC code: 85101508).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Motorized cycles", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Motorized cycles", Description = "Covers motorcycles, scooters and mopeds (UNSPSC codes: 25101801-04).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Police vehicles", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Police vehicles", Description = "Vehicle for the explicit use for police and law enforcement (UNSPSC code: 25101702).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Spare parts kits for vehicles û sedans, pick-ups, trucks, motorcycles, etc.", OutputGroup = "Goods", OutputSubGroup = "Motorized land vehicles", OutputName = "Spare parts kits for vehicles û sedans, pick-ups, trucks, motorcycles, etc.", Description = "Spare part kits and accessories for all motorized vehicle types.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Non-medical measuring and observing and testing (laboratory) equipment", OutputGroup = "Goods", OutputSubGroup = "Non-medical laboratory and measuring equipment", OutputName = "Non-medical measuring and observing and testing (laboratory) equipment", Description = "Measuring, observing and testing equipment for non-medical purposes (UNSPSC codes: 41110000-6502 [excluding codes 41115800-68 for medical measuring]).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Office Furniture and accessories", OutputGroup = "Goods", OutputSubGroup = "Office", OutputName = "Office Furniture and accessories", Description = "The movable articles that are used to make a room or building suitable for working in, such as tables, chairs, desks, cabinets and shelving (UNSPSC: 56101701-19).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Office machines and their supplies and accessories", OutputGroup = "Goods", OutputSubGroup = "Office", OutputName = "Office machines and their supplies and accessories", Description = "Covers among others; photocopiers, dry erase boards or accessories and adding machines (UNSPSC codes: 44101500-904).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Other vehicles", OutputGroup = "Goods", OutputSubGroup = "Other vehicles", OutputName = "Other vehicles", Description = "Covers among others; bicycles (UNSPSC codes: 25161505-07); rescue ships/boats (UNSPSC code: 25111603); and all other vehicles not included under motorized land vehicles outputs.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Power generators", OutputGroup = "Goods", OutputSubGroup = "Power generators", OutputName = "Power generators", Description = "Covers among others; diesel generators, hydro-electric generators, wind generators, gas generators, thermal generators, hydraulic generators, solar generators and others (UNSPSC codes: 26111601-13).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Safety and security equipment, uniforms, supplies and accessories", OutputGroup = "Goods", OutputSubGroup = "Safety and security", OutputName = "Safety and security equipment, uniforms, supplies and accessories", Description = "Covers among others; metal detectors (UNSPSC code: 41111903); crowd control equipment, security and control equipment, forensic equipment, explosives control equipment (UNSPSC codes: 46150000-46151802); public safety and control equipment (UNSPSC code:  46160000-1715); security, surveillance and detection equipment (UNSPSC code: 46170000-1701); personal and fire protection equipment and accesories (UNSPSC codes: 46180000-191625); uniforms (UNSPSC codes: 53102700-18).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "UN WebBuy Plus (Goods)", OutputGroup = "Goods", OutputSubGroup = "UN WebBuy Plus", OutputName = "UN WebBuy Plus (Goods)", Description = "Covers the goods and equipment procured by only the UN WebBuy Plus projects.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Water and wastewater treatment supply and disposal items", OutputGroup = "Goods", OutputSubGroup = "Water, weather and geological", OutputName = "Water and wastewater treatment supply and disposal items", Description = "Covers among others; collection tanks, septic tanks and carbon filtration equipment (UNSPSC codes: 47101501-615).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Grantee selection and grants management", OutputGroup = "Grants", OutputSubGroup = "Grantee selection and grants management", OutputName = "Grantee selection and grants management", Description = "Solicitation (if applicable), evaluation of proposals, recommendation of implementing partner(s), issuance of applicable non-procurement fund disbursement agreement (including Grant Support Agreements), monitoring, financial management and auditing (if applicable) of the grant(s) and other non procurement fund disbursement activities.", UnitId = no, ProjectCategoryId = cat2, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Grants management under ad-hoc selection", OutputGroup = "Grants", OutputSubGroup = "Grants management under ad-hoc selection", OutputName = "Grants management under ad-hoc selection", Description = "Selection of implementing partners under exceptions to the competitive process or a tailored selection methodology, evaluation of proposals, recommendation of implementing partners issuance of non-procurement disbursement agreement (GSA/PCA/UN2UN), monitoring, financial management and auditing (if applicable) of the grants and/or funding and other non-procurement fund disbursement activities.", UnitId = no, ProjectCategoryId = cat2, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Grants management under preselection", OutputGroup = "Grants", OutputSubGroup = "Grants management under preselection", OutputName = "Grants management under preselection", Description = "Issuance of applicable non-procurement fund disbursement agreement (including Grant Support Agreement), monitoring, financial management and auditing (if applicable) of the grant(s) and other non procurement fund disbursement activities.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "HR contract management and recruitment", OutputGroup = "HR contract(s)", OutputSubGroup = "HR contract(s)", OutputName = "HR contract management and recruitment", Description = "Solicitation, evaluation and/or recommendation of applicants, issuing HR contracts. Excluding daily-wage contracts for infrastructure implementation.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Human resources", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "HR contract management under preselection", OutputGroup = "HR contract(s)", OutputSubGroup = "HR contract(s)", OutputName = "HR contract management under preselection", Description = "Issuance of HR contracts through a specific partner request for service.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Human resources", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Camp", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Accommodation facilities", OutputName = "Camp", Description = "Facility intended for short term non-permanent use and may be comprised of tents, containers, rudimentary shelters. It usually contains accommodations, ablutions, administrative and sometimes security facilities.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Emergency shelter", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Accommodation facilities", OutputName = "Emergency shelter", Description = "Collection of self-built shelters or simple planned facilities provided for emergency use.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Housing", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Accommodation facilities", OutputName = "Housing", Description = "Room or group of related rooms, designed for use as a dwelling. Normally counted singly but may be combined within a single larger building.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Aviation intelligent system", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Airports", OutputName = "Aviation intelligent system", Description = "Flight traffic control, information and lighting systems designed to provide increased safety for aircraft movement in the air and on the ground.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Landing strip", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Airports", OutputName = "Landing strip", Description = "Sealed or unsealed aircraft landing zone normally with basic capacity and minimal facilities.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Runway", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Airports", OutputName = "Runway", Description = "Sealed or unsealed surface laid on graded base material specifically prepared for the landing and take-off of aircraft.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Coastal defensive works", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Coastal protection systems", OutputName = "Coastal defensive works", Description = "Barrier built out into the sea, with the explicit purpose of breaking waves, to protect a coast or harbour from the force of waves.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "School (Primary/Secondary)", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Educational facilities", OutputName = "School (Primary/Secondary)", Description = "Institution for development of a childÆs education generally from 5 yrs old to 16 yrs old.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Teacher training centre", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Educational facilities", OutputName = "Teacher training centre", Description = "Facility for the purpose of training teachers for specific educational subjects.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "University facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Educational facilities", OutputName = "University facility", Description = "Institution of learning of the highest level, having a program of graduate studies together with several professional schools such as law, medicine, and engineering, and authorized to confer both undergraduate and graduate degrees.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Vocational training centre", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Educational facilities", OutputName = "Vocational training centre", Description = "Facility for the purpose of training and preparing people for a specific technical trade or service industry.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Levee/barrier", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Flood control and drainage facilities", OutputName = "Levee/barrier", Description = "Embankment built to prevent the overflow of a body of water or contain its encroachment into other areas, e.g. a river.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Pumping station", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Flood control and drainage facilities", OutputName = "Pumping station", Description = "Facility including pumps and equipment for pumping utilized for flood control and drainage purpose.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Riverbank stabilization system", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Flood control and drainage facilities", OutputName = "Riverbank stabilization system", Description = "Planned structure and/or process established for stabilization of land alongside a body of water such as a river or canal particularly those affected by erosion.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Sub-surface drainage system (Flood Control and Drainage)", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Flood control and drainage facilities", OutputName = "Sub-surface drainage system (Flood Control and Drainage)", Description = "System which provides removal of sub surface water from within an area or stops encroachment of water from adjacent areas.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Surface drainage channel", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Flood control and drainage facilities", OutputName = "Surface drainage channel", Description = "System which provides removal of surface water from within an area or stops encroachment of water from adjacent areas.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Health clinic", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Health facilities", OutputName = "Health clinic", Description = "Health care facility that is primarily devoted to the care of \"outpatients\" and short term medical appointments. These may be more comprehensive in situations where hospitals are not available to support health.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Hospital", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Health facilities", OutputName = "Hospital", Description = "Institution generally divided into multiple departments in which sick or injured persons are given significant medical or surgical treatment.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Laboratory", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Health facilities", OutputName = "Laboratory", Description = "Facility that provides controlled conditions in which scientific testing, research, experiments may be performed.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Medical warehouse", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Health facilities", OutputName = "Medical warehouse", Description = "Specialised building for storage of vaccines, medicines and other types of medical supplies.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Specialist facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Health facilities", OutputName = "Specialist facility", Description = "Health care facility which is specialized in certain practices.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Dam", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Irrigation systems", OutputName = "Dam", Description = "Over ground, large scale water storage facility comprising a barrier that impounds water from natural catchment zones, rivers or streams.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Ground water recharge", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Irrigation systems", OutputName = "Ground water recharge", Description = "Structure and/or process established for management of water discharge into subsurface aquifer.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Head works", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Irrigation systems", OutputName = "Head works", Description = "Apparatus for controlling the flow and direction of water to be diverted for irrigation purposes.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Retention pond", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Irrigation systems", OutputName = "Retention pond", Description = "Storm water management facility providing retention of water runoff for future use in irrigation or water supply.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Surface irrigation", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Irrigation systems", OutputName = "Surface irrigation", Description = "System which enables the surface distribution of water to the land surfaces via channels or spray systems.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Landslip recovery", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Land Remediation", OutputName = "Landslip recovery", Description = "Removal of debris and slip material, stabilisation, remediation and revegetation of affected areas", UnitId = hectares, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Canal", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Ports, harbours, inland waterways", OutputName = "Canal", Description = "Artificial waterway constructed to allow the passage of boats or ships inland or to convey water for irrigation.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Cargo/commercial port", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Ports, harbours, inland waterways", OutputName = "Cargo/commercial port", Description = "Large port where ships can dock and transfer commercial or containerised cargo, which has to be loaded and unloaded by significant mechanical equipment.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Docking/quay facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Ports, harbours, inland waterways", OutputName = "Docking/quay facility", Description = "Structure which does not qualify as a port, built on the land next to a river, lake, or ocean that is used as a place for boats to stop for loading and unloading freight and passengers.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Fishery port", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Ports, harbours, inland waterways", OutputName = "Fishery port", Description = "Fishing port is a smaller port or harbour for landing, processing and distributing fish. It may be a recreational facility, but it is usually small scale commercial.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Passenger port", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Ports, harbours, inland waterways", OutputName = "Passenger port", Description = "Large port where passenger ships can dock to enable passengers to board and depart from ships.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "LV/MV Distribution network", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power distribution facilities", OutputName = "LV/MV Distribution network", Description = "Final stage in the delivery of electric power; it carries electricity from the generation or transmission system to individual consumers", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Bulk fuel storage facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power generation facilities", OutputName = "Bulk fuel storage facility", Description = "Large scale storage tanks in tank farms that hold liquids, compressed gases for the short- or long-term storage of fuel.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Diesel generator support structure", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power generation facilities", OutputName = "Diesel generator support structure", Description = "Structures intended to house or support medium to small scale diesel engines which produces electrical power for small areas or specific facilities.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Hydro power plant", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power generation facilities", OutputName = "Hydro power plant", Description = "Large or small scale facility which produces electrical power through the use of the gravitational force of falling or flowing water.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Renewable energy mini grid", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power generation facilities", OutputName = "Renewable energy mini grid", Description = "An independant energy system which produces, stores and distributes electrical power through the use of renewable energy sources, e.g. wind, sunlight, biomass or water to a localised area", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Renewable energy plant", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power generation facilities", OutputName = "Renewable energy plant", Description = "Large or small scale facility which produces electrical power through the use of the renewable energy sources, e.g. wind, sunlight, biomass or wave.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "HV Power Line", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power transmission facilities", OutputName = "HV Power Line", Description = "High voltage electrical cables used to transmit electrical energy for long distances.", UnitId = km, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Transformer/substation", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Power transmission facilities", OutputName = "Transformer/substation", Description = "An electrical device that transfers electrical energy between two or more circuits through electromagnetic induction. Transformers increase or decrease the voltages of alternating current in electric power applications.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Administrative office", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Public realm facilities", OutputName = "Administrative office", Description = "Facility used by civil servants for the delivery of administrative support to government activity.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Community centre", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Public realm facilities", OutputName = "Community centre", Description = "Building used by members of a community for social gatherings, educational activities, etc.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Market", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Public realm facilities", OutputName = "Market", Description = "Open place or a covered building where buyers and sellers convene for the sale of goods.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Museum", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Public realm facilities", OutputName = "Museum", Description = "Facility that cares for collections and other objects of artistic, cultural, historical, or scientific importance and makes them available for public viewing.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Park/garden", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Public realm facilities", OutputName = "Park/garden", Description = "Area of land for the enjoyment of the public, having facilities for rest and recreation, often owned, set apart, and managed by a city, state, or nation.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Sanitation centre", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Public realm facilities", OutputName = "Sanitation centre", Description = "Public facility which contains sanitation units such as toilets, showers and laundry facilities.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Sport stadium/sporting facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Public realm facilities", OutputName = "Sport stadium/sporting facility", Description = "Place or venue for (mostly) outdoor sports and consists of a field or stage either partly or completely surrounded by a tiered structure designed to allow spectators to stand or sit and view the event.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Rail bridge", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Railways and bridges", OutputName = "Rail bridge", Description = "Structure which carries a railway over a river, road, or other obstacle.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Railroad", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Railways and bridges", OutputName = "Railroad", Description = "Set of rails on a sub base material, commonly in one or more pairs.", UnitId = km, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Culvert/road drainage", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Culvert/road drainage", Description = "Discharge channel that transfers water from one side of the road to the other normally connected to roadside drains removing water from the road surface.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Highway", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Highway", Description = "Main road, a significant arterial connection, normally sealed and designed for higher speed and load capacity connecting towns and/or cities.", UnitId = km, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Paved road", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Paved road", Description = "Durable sealed surface laid over graded base material for vehicular or foot traffic.", UnitId = km, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Pedestrian bridge", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Pedestrian bridge", Description = "Structure which carries pedestrian traffic over a river, road, or other obstacle.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Road bridge", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Road bridge", Description = "Structure which carries vehicle traffic over a river, road, or other obstacle.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Road safety barrier/structure", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Road safety barrier/structure", Description = "Protective barrier, speed bumps or similar that act as protective traffic control/ calming mechanisms.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Road tunnel", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Road tunnel", Description = "Enclosed passageway for vehicle traffic, which may be dug through the surrounding soil/earth/rock.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Street lighting", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Street lighting", Description = "Elevated source of light on the edge of, or suspended over a road or walkway.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Unpaved road", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Roads and bridges", OutputName = "Unpaved road", Description = "An unsealed surface laid over graded base material for vehicular or foot traffic.", UnitId = km, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Courthouse", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Rule of law facilities", OutputName = "Courthouse", Description = "Building in which rule of law is administered in one or more courtrooms. May contain prisoner facilities, offices.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Custom/border control facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Rule of law facilities", OutputName = "Custom/border control facility", Description = "Facility on the border between countries, states, provinces, or in the section of an airport, station, etc., where goods, vehicles and/or people passing through are monitored.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Police station", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Rule of law facilities", OutputName = "Police station", Description = "Facility from which police officers are dispatched and to which persons under arrest are brought. May contain staff accommodation and training facilities.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Police training facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Rule of law facilities", OutputName = "Police training facility", Description = "Facility in which police can be trained in theoretical and/or practical subjects.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Prison/detention facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Rule of law facilities", OutputName = "Prison/detention facility", Description = "Building for the confinement of persons held while awaiting trial, persons sentenced after conviction, and associated staff and administration facilities", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Specialized equipment", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Specialized equipment", OutputName = "Specialized equipment", Description = "Covers among others, medical measuring and observing and testing equipment, renewable energy equipment, other specialized hydraulic and/or mechanical and/or electrical equipment requiring fixed connections to services.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Agricultural centre", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Storage/industrial facilities", OutputName = "Agricultural centre", Description = "Centre specifically formed to organize, support, house or manage agricultural activities.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Hangar", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Storage/industrial facilities", OutputName = "Hangar", Description = "Closed building structure to hold large size industrial goods or transport related vehicles such as aircraft, buses or military vehicles.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Industrial zone", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Storage/industrial facilities", OutputName = "Industrial zone", Description = "Area zoned and planned for the purpose of industrial development.", UnitId = km2, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Logistics hub", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Storage/industrial facilities", OutputName = "Logistics hub", Description = "Place used as a logistic centre, operational hub or cross dock/ transhipment building for goods.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Materials/metrology laboratory", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Storage/industrial facilities", OutputName = "Materials/metrology laboratory", Description = "Facility that provides controlled conditions in which scientific and industrial measurement can be performed normally for material sciences.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Sustainable agricultural land", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Storage/industrial facilities", OutputName = "Sustainable agricultural land", Description = "Agricultural land that provides efficient production of agricultural products, in a way that protects the natural environment, the social and economic conditions of local communities, and safeguards the welfare of all farmed species.", UnitId = km2, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Warehouse", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Storage/industrial facilities", OutputName = "Warehouse", Description = "Building for storage and transhipping of goods/industrial products.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Data centre", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Telecom services", OutputName = "Data centre", Description = "Facility where ICT infrastructure is located and/or managed.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "ICT system installation", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Telecom services", OutputName = "ICT system installation", Description = "Refers to an assemblage of communication devices or applications, including, but not limited to: radio, television, cellular phones, computer and network hardware and software or satellite systems. Including associated cabling. The number refers to an entire system, including any sub-components.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Secured/protected facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "UN buildings", OutputName = "Secured/protected facility", Description = "Constructed facility which offers elements of security or protection which other constructed facilities do not offer.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "UN office", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "UN buildings", OutputName = "UN office", Description = "Room, a building or other area used by the UN.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Waste collection system", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste  collection & separation facilities", OutputName = "Waste collection system", Description = "System for managing waste streams such as chemicals, oils, electrical goods, paints, paper etc. Associated planning to establish system includes to determine collection methods, capacity of systems, recycling methodologies.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Incineration plant", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste disposal facilities", OutputName = "Incineration plant", Description = "Facility where waste is destroyed using high temperature furnaces. The heat from the combustion process may be used to generate electricity or provide large scale heating where feasible. Use waste to energy in this instance.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Landfill site development", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste disposal facilities", OutputName = "Landfill site development", Description = "Site for the disposal of waste materials by burial which can also be used for waste management purposes, such as the temporary storage, consolidation and transfer, or processing of waste material (sorting, treatment, or recycling).", UnitId = km2, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Leachate and gas emission system", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste disposal facilities", OutputName = "Leachate and gas emission system", Description = "Set of plans, structures and/or process established for management or recycling/ cleansing of contaminated liquid or gas emissions that contain harmful substances that may enter the environment.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Composting facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste processing facilities", OutputName = "Composting facility", Description = "Facility to stockpile organic matter for decomposition and recycling into fertilizer and soil products.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Recycling facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste processing facilities", OutputName = "Recycling facility", Description = "Place where different types of sorted waste can be stockpiled and treated for partial or complete re-use.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Waste-to-energy facility", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste processing facilities", OutputName = "Waste-to-energy facility", Description = "Waste management facility which combusts wastes to produce electricity.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Drainage system (waste water)", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste water systems", OutputName = "Drainage system (waste water)", Description = "System enabling the discharge of wastewater from built up areas to a treatment facility.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Latrine", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste water systems", OutputName = "Latrine", Description = "Toilet or simple facility within a sanitation system. It can be a communal trench in the earth in a camp, a hole in the ground (pit), or similar non mechanical systems.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Packaged WWT system", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste water systems", OutputName = "Packaged WWT system", Description = "Self-contained smaller scale plant providing a process of treating waste, (e.g. from household sewage). It includes physical, chemical, and biological processes to produce environmentally safe treated waste.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Waste water treatment plant", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Waste water systems", OutputName = "Waste water treatment plant", Description = "Facility to treat wastewater so that can be either returned to the water cycle with minimal environmental issues or reused.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Aquifer management", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water resources management systems", OutputName = "Aquifer management", Description = "Set of plans, structures and/or process established for management of an underground layer of water-bearing permeable rock or unconsolidated materials from which groundwater can be extracted using a well or bore.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Watershed management", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water resources management systems", OutputName = "Watershed management", Description = "Activities associated with definition of catchment zones, water management characteristics for water flowing to rivers, basins, or seas.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Wetland/water park", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water resources management systems", OutputName = "Wetland/water park", Description = "Land that has a wet and spongy soil, such as a marsh, swamp, or bog used to slow water discharge rates, biologically cleanse water and provide natural habitat.", UnitId = km2, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Borehole", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water sourcing systems", OutputName = "Borehole", Description = "Narrow hole which is drilled significantly deeper compared to a well, and later lined with pipes and supplied with a pumping mechanism, for the purpose of obtaining water from the earth.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Hafir (water sourcing)", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water sourcing systems", OutputName = "Hafir (water sourcing)", Description = "An underground reservoir designed for storing rain water carried by streams.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Rain catchment system", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water sourcing systems", OutputName = "Rain catchment system", Description = "System used for the accumulation and deposition of rainwater for reuse on-site, rather than allowing it to run off.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Well", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water sourcing systems", OutputName = "Well", Description = "Wider hole dug, at times by hand, usually somewhere between 5 to 10 meters deep, for the purpose of obtaining water from the earth.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Water distribution pipe network", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water treatment & distribution systems", OutputName = "Water distribution pipe network", Description = "Secondary system of hydraulic pipework, usually smaller pipes, and control components which enables broad distribution of water to individual premises and facilities.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Water storage/reservoir", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water treatment & distribution systems", OutputName = "Water storage/reservoir", Description = "Bulk storage structure or significant water retention facility for storing water for the purposes of later distribution.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Water supply main network", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water treatment & distribution systems", OutputName = "Water supply main network", Description = "Primary system of hydraulic pipework, usually bigger high pressure pipes, and control components which provide bulk water supply.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Water treatment plant", OutputGroup = "Infrastructure physical asset(s)", OutputSubGroup = "Water treatment & distribution systems", OutputName = "Water treatment plant", Description = "Facility which filters and decontaminates water to an approved standard suitable for an end-use.", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Design of infrastructure asset(s)", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Design of infrastructure asset(s)", Description = "Preparation of concept, preliminary and detailed design documents normally comprised of design brief, design reports, drawings, specifications and Bills of Quantities", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Design Reviews and Reports", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Design Reviews and Reports", Description = "Implementation of design reviews and any associated reports for asset designs prepared by other entities", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Engineering Accreditation and reporting", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Engineering Accreditation and reporting", Description = "Preparation of engineering accreditation criteria, their assessment and recommendations including any associated reports", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Engineering Testing and investigation", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Engineering Testing and investigation", Description = "Implementation of sample collection, testing and investigation processes and associated reports for either materials or construction processes", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Multi or specific sector Infrastructure Assessment", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Multi or specific sector Infrastructure Assessment", Description = "Use of the Infrastructure Assessment methodology in one or more sectors to prepare condition and functionality reports for existing infrastructure", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Multi sectoral analysis and planning", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Multi sectoral analysis and planning", Description = "Use of the Capacity Assessment tool for analysis planning and prioritisation of new infrastructure work", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Standards and regulations development", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Standards and regulations development", Description = "Preparation of new technical standards and or regulations with associated reports", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Technical Studies and Reports", OutputGroup = "Infrastructure technical output(s)", OutputSubGroup = "Infrastructure technical output(s)", OutputName = "Technical Studies and Reports", Description = "Preparation of specific studies or reports on infrastructure topics or asset types", UnitId = no, ProjectCategoryId = cat3, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Communication and outreach products and services", OutputGroup = "Project Management", OutputSubGroup = "Communications and outreach items", OutputName = "Communication and outreach products and services", Description = "Products or services that serve to promote or communicate purpose or other information of a project, programme, sector or organization. Example products are broadcasts, web pages, brochures and other publications. Example services are events, meetings and workshops.", UnitId = no, ProjectCategoryId = cat2, OutputServiceLine = "Project Management", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Missions", OutputGroup = "Project Management", OutputSubGroup = "Missions organised", OutputName = "Missions", Description = "Assisting partners with travel arrangements, including transport and any associated lodging and security arrangements. The number refers to the number of missions and not number of flights or travellers.", UnitId = no, ProjectCategoryId = cat2, OutputServiceLine = "Project Management", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "PMO", OutputGroup = "Project Management", OutputSubGroup = "Portfolio, programme or project management office (PMO)", OutputName = "PMO", Description = "An office which can provide strategic planning, delivery support and centre of excellence functions and services.", UnitId = no, ProjectCategoryId = cat2, OutputServiceLine = "Project Management", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "PMT", OutputGroup = "Project Management", OutputSubGroup = "Project Management Team (PMT)", OutputName = "PMT", Description = "A team that provides project implementation on behalf of a partner organization.", UnitId = no, ProjectCategoryId = cat2, OutputServiceLine = "Project Management", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Demining and disarmament services", OutputGroup = "Service Contract(s)", OutputSubGroup = "Service Contract(s)", OutputName = "Demining and disarmament services", Description = "Covers among others; minefield and demining services, canine explosive detection team, Explosive Detection Dogs (EDD) with handler (UNSPSC codes: 81102800-81102815); disarmament services, stockpile destruction, mine action center MAC or mine action coordination center MACC service, mine victim or survivor assistance service, physical security and stockpile management PSSM service, landmine prohibition action and explosive remnants of war risk education (UNSPSC codes: 92111600-16).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Safety and security services", OutputGroup = "Service Contract(s)", OutputSubGroup = "Service Contract(s)", OutputName = "Safety and security services", Description = "Covers among others; peace keeping operations (UNSPSC code: 92111502); safety and security system installation services (UNSPSC codes: 72151700-04); security and personal safety services (UNSPSC codes: 92120000-1802).", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Service contract - other", OutputGroup = "Service Contract(s)", OutputSubGroup = "Service Contract(s)", OutputName = "Service contract - other", Description = "Agreement whereby a contractor provides time, effort, and/or expertise not captured under other service contract outputs.", UnitId = no, ProjectCategoryId = cat1, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Training: Finance", OutputGroup = "Training days", OutputSubGroup = "Training delivery: finance", OutputName = "Training: Finance", Description = "Providing training in person or in a virtual format. The training contents may be developed by UNOPS or provided by a third party. The number of training days refers to the duration of the training event itself. A training day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Financial", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Training: HR", OutputGroup = "Training days", OutputSubGroup = "Training delivery: HR", OutputName = "Training: HR", Description = "Providing training in person or in a virtual format. The training contents may be developed by UNOPS or provided by a third party. The number of training days refers to the duration of the training event itself. A training day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Human resources", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Training: Infrastructure", OutputGroup = "Training days", OutputSubGroup = "Training delivery: infrastructure", OutputName = "Training: Infrastructure", Description = "Providing training in person or in a virtual format. The training contents may be developed by UNOPS or provided by a third party. The number of training days refers to the duration of the training event itself. A training day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Infrastructure", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Training: Procurement", OutputGroup = "Training days", OutputSubGroup = "Training delivery: procurement", OutputName = "Training: Procurement", Description = "Providing training in person or in a virtual format. The training contents may be developed by UNOPS or provided by a third party. The number of training days refers to the duration of the training event itself. A training day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Procurement", Status = EntityStatus.Active, IsDeleted = false });
        outputs.Add(new Output { Name = "Training: Project Management", OutputGroup = "Training days", OutputSubGroup = "Training delivery: project management", OutputName = "Training: Project Management", Description = "Providing training in person or in a virtual format. The training contents may be developed by UNOPS or provided by a third party. The number of training days refers to the duration of the training event itself. A training day is composed of eight hours of work.", UnitId = days, ProjectCategoryId = cat2, OutputServiceLine = "Project Management", Status = EntityStatus.Active, IsDeleted = false });

        return outputs;
    }
}
